name: GitHub profile summary cards

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate summary cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Kk4747
          UTC_OFFSET: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
